name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: srid
    - name: Build neuron site 🔧
      run: |
        cd ./guide
        mkdir -p .neuron/output && touch .neuron/output/.nojekyll
        docker run -v $PWD:/notes sridca/neuron neuron gen --pretty-urls
    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: guide/.neuron/output
